//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Production_of_semi_finished_products
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ID { get; set; }
        public string Data { get; set; }
        public string Condition { get; set; }
        public string Proprietor { get; set; }
        public string Comment { get; set; }
    }
}
